server:
  port: 8080


spring:

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Grud?createDatabaseIfNotExist=true
    username: root
    password: testtest1